// This is a simplified version of what would typically be generated by contentlayer
// In a real implementation, you would use contentlayer to process MDX files

export interface Post {
  slug: string
  title: string
  description: string
  date: string
  image?: string
  imageCaption?: string
  author: string
  authorImage?: string
  readingTime: string
  categories: string[]
  body: {
    code: string
  }
}

// Sample posts data
export const allPosts: Post[] = [
  {
    slug: "living-as-an-expat-in-berlin",
    title: "Living as an Expat in Berlin: A Comprehensive Guide",
    description:
      "Everything you need to know about moving to and living in Berlin as an expatriate, from housing to healthcare and beyond.",
    date: "2023-04-15",
    image: "/placeholder.svg?height=630&width=1200",
    imageCaption: "The iconic Brandenburg Gate in Berlin, Germany",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "8",
    categories: ["Expat Life", "European Travel"],
    body: {
      code: "This is a sample blog post about living as an expat in Berlin.",
    },
  },
  {
    slug: "top-tech-hubs-in-europe",
    title: "The Top 10 Tech Hubs in Europe for Digital Nomads",
    description:
      "Discover the best European cities for tech professionals and digital nomads, with insights on co-working spaces, networking opportunities, and quality of life.",
    date: "2023-04-10",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "10",
    categories: ["Tech Insights", "Expat Life"],
    body: {
      code: "This is a sample blog post about tech hubs in Europe.",
    },
  },
  {
    slug: "hidden-gems-in-southern-spain",
    title: "Hidden Gems: Exploring Southern Spain Off the Beaten Path",
    description:
      "Venture beyond the tourist hotspots and discover the authentic charm of Andalusia's lesser-known towns and natural wonders.",
    date: "2023-04-05",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "7",
    categories: ["European Travel"],
    body: {
      code: "This is a sample blog post about hidden gems in Southern Spain.",
    },
  },
  {
    slug: "navigating-healthcare-systems-in-europe",
    title: "Navigating Healthcare Systems Across Europe: A Country-by-Country Guide",
    description:
      "A comprehensive comparison of healthcare systems in major European countries, with practical advice for expatriates and travelers.",
    date: "2023-03-28",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "12",
    categories: ["Expat Life", "European Travel"],
    body: {
      code: "This is a sample blog post about healthcare systems in Europe.",
    },
  },
  {
    slug: "ai-startups-transforming-european-industries",
    title: "How AI Startups Are Transforming European Industries",
    description:
      "An in-depth look at the innovative AI companies reshaping sectors from healthcare to finance across the European continent.",
    date: "2023-03-20",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "9",
    categories: ["Tech Insights"],
    body: {
      code: "This is a sample blog post about AI startups in Europe.",
    },
  },
  {
    slug: "european-film-festivals-guide",
    title: "The Ultimate Guide to European Film Festivals",
    description:
      "From Cannes to Berlin, discover the most prestigious and exciting film festivals across Europe, with tips on how to attend as a visitor.",
    date: "2023-03-15",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "8",
    categories: ["Entertainment", "European Travel"],
    body: {
      code: "This is a sample blog post about European film festivals.",
    },
  },
  {
    slug: "remote-work-friendly-cities-in-europe",
    title: "The Most Remote Work-Friendly Cities in Europe",
    description:
      "Evaluating European cities based on internet speed, co-working spaces, cost of living, and quality of life for remote workers.",
    date: "2023-03-10",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "11",
    categories: ["Expat Life", "Tech Insights"],
    body: {
      code: "This is a sample blog post about remote work-friendly cities in Europe.",
    },
  },
  {
    slug: "european-culinary-traditions",
    title: "A Journey Through Europe's Culinary Traditions",
    description:
      "Explore the rich and diverse food cultures across European regions, from Mediterranean delicacies to Nordic cuisine.",
    date: "2023-03-05",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "10",
    categories: ["European Travel", "Entertainment"],
    body: {
      code: "This is a sample blog post about European culinary traditions.",
    },
  },
  {
    slug: "european-tech-policy-changes",
    title: "How Recent EU Tech Policy Changes Affect Global Companies",
    description:
      "An analysis of the latest European Union regulations on technology and their implications for international businesses and consumers.",
    date: "2023-02-28",
    image: "/placeholder.svg?height=630&width=1200",
    author: "Mind & Muster",
    authorImage: "/placeholder.svg?height=100&width=100",
    readingTime: "9",
    categories: ["Tech Insights"],
    body: {
      code: "This is a sample blog post about EU tech policy changes.",
    },
  },
]
